# Conda environment file for the project with pytorch, jupyter, transformers, and datasets

name: pytorch

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8.18
  - pip=23.3=pyhd8ed1ab_0
  - pip:
      # dev dependencies
      - pre-commit==3.5.0
      - black==23.10.0
      - isort==5.12.0
