# Conda environment file for the project with pytorch, jupyter, transformers, and datasets

name: pytorch

channels:
  - pytorch
  - conda-forge
  - defaults

dependencies:
  - python=3.8.18
  - pip=23.3=pyhd8ed1ab_0
  - jupyter=1.0.0=pyhd8ed1ab_10
  - jupyterlab=4.0.7=pyhd8ed1ab_0
  - pip:
      - accelerate==0.23.0
      - datasets==2.14.5
      - evaluate==0.4.1
      - scikit-learn==1.3.1
      - torch==2.1.0
      - transformers==4.34.0
      # dev dependencies
      - pre-commit==3.5.0
      - black==23.10.0
      - isort==5.12.0
